### ISSUE TITLE
Incorrect contract?

### ISSUE THREAD

**Issue by tcolgate** [sbinet/go2-test#1]
https://github.com/sbinet/go2-test/blob/5d5b17dde62f0006ed4c933cc7dcc91e88878b65/ndarray/nd.go#L4

If this is intended to be some numeric type, then you might want `*=` maybe? 
https://play.golang.org/p/DXOcEwi-o-p

**Comment by sbinet** [comment]
eventually, yes.

but at the moment, I believe the contract is correct.
`ndarray.Array` only needs `T` to be addable via the `Sum` method.
